package uz.mirix.envcheck;

import java.math.BigDecimal;
import java.net.URI;
import java.time.Duration;
import java.util.*;
import java.util.regex.Pattern;

final class EnvValidator {
    private static final Pattern HOSTNAME=Pattern.compile("^(?=.{1,253}$)(?!-)(?:[a-zA-Z0-9-]{1,63}\\.)*[a-zA-Z0-9][a-zA-Z0-9-]{0,62}$");
    private static final Pattern IPV4=Pattern.compile("^(?:25[0-5]|2[0-4]\\d|1?\\d?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|1?\\d?\\d)){3}$");
    private static final Pattern SIZE=Pattern.compile("^(\\d+(?:\\.\\d+)?)\\s*(B|KB|MB|GB|TB|KIB|MIB|GIB|TIB)?$",Pattern.CASE_INSENSITIVE);
    private static final Pattern SHORT_DURATION=Pattern.compile("^(\\d+)\\s*(MS|S|M|H|D)$",Pattern.CASE_INSENSITIVE);
    ValidationResult validate(EnvSchema schema,ValueResolver resolver){List<EnvCheckResult> checks=new ArrayList<>();for(EnvRule rule:schema.rules())checks.add(validateRule(rule,resolver));return new ValidationResult(checks);}
    private EnvCheckResult validateRule(EnvRule rule,ValueResolver resolver){Optional<String> resolved=resolver.resolve(rule.propertyKey());if(resolved.isEmpty()){List<EnvViolation> v=rule.required()?List.of(new EnvViolation(rule.name(),ViolationCode.MISSING,"missing")):List.of();return new EnvCheckResult(rule.name(),rule.propertyKey(),false,rule.sensitive(),"",v);}String value=resolved.get();List<EnvViolation> v=new ArrayList<>();if(!rule.allowBlank()&&value.isBlank())v.add(new EnvViolation(rule.name(),ViolationCode.BLANK,"must not be blank"));if(!value.isBlank()){validateType(rule,value,v);validateConstraints(rule,value,v);}return new EnvCheckResult(rule.name(),rule.propertyKey(),true,rule.sensitive(),rule.sensitive()?"[REDACTED]":value,v);}
    private void validateType(EnvRule rule,String value,List<EnvViolation> v){try{switch(rule.type()){case STRING->{} case INTEGER->Integer.parseInt(value);case LONG->Long.parseLong(value);case BOOLEAN->{if(!("true".equalsIgnoreCase(value)||"false".equalsIgnoreCase(value)))throw new IllegalArgumentException();}case URI->validateUri(value,false);case URL->validateUri(value,true);case HOST->{if(!(IPV4.matcher(value).matches()||HOSTNAME.matcher(value).matches()||"localhost".equalsIgnoreCase(value)))throw new IllegalArgumentException();}case PORT->{int p=Integer.parseInt(value);if(p<1||p>65535)throw new IllegalArgumentException();}case DURATION->parseDuration(value);case SIZE->parseSize(value);}}catch(RuntimeException ex){v.add(new EnvViolation(rule.name(),ViolationCode.INVALID_TYPE,typeMessage(rule.type())));}}
    private void validateConstraints(EnvRule rule,String value,List<EnvViolation> v){if(rule.minLength()!=null&&value.length()<rule.minLength())v.add(new EnvViolation(rule.name(),ViolationCode.TOO_SHORT,"too short (min "+rule.minLength()+")"));if(rule.maxLength()!=null&&value.length()>rule.maxLength())v.add(new EnvViolation(rule.name(),ViolationCode.TOO_LONG,"too long (max "+rule.maxLength()+")"));if(rule.pattern()!=null&&!rule.pattern().matcher(value).matches())v.add(new EnvViolation(rule.name(),ViolationCode.PATTERN_MISMATCH,"pattern mismatch"));if(!rule.allowedValues().isEmpty()&&!rule.allowedValues().contains(value))v.add(new EnvViolation(rule.name(),ViolationCode.NOT_ALLOWED,"must be one of "+rule.allowedValues()));if(rule.min()!=null||rule.max()!=null){try{BigDecimal n=numericValue(rule.type(),value);if(rule.min()!=null&&n.compareTo(rule.min())<0)v.add(new EnvViolation(rule.name(),ViolationCode.TOO_SMALL,"must be >= "+rule.min().toPlainString()));if(rule.max()!=null&&n.compareTo(rule.max())>0)v.add(new EnvViolation(rule.name(),ViolationCode.TOO_LARGE,"must be <= "+rule.max().toPlainString()));}catch(RuntimeException ignored){}}for(CustomValidator validator:rule.customValidators())validator.validate(value).ifPresent(m->v.add(new EnvViolation(rule.name(),ViolationCode.CUSTOM,m)));}
    private static BigDecimal numericValue(EnvType type,String value){return switch(type){case INTEGER,LONG,PORT->new BigDecimal(value);case SIZE->parseSize(value);case DURATION->BigDecimal.valueOf(parseDuration(value).toMillis());default->new BigDecimal(value);};}
    private static void validateUri(String value,boolean url){URI uri=URI.create(value);if(!uri.isAbsolute())throw new IllegalArgumentException();if(url&&("http".equalsIgnoreCase(uri.getScheme())||"https".equalsIgnoreCase(uri.getScheme()))&&uri.getHost()==null)throw new IllegalArgumentException();}
    private static Duration parseDuration(String value){String t=value.trim();if(t.regionMatches(true,0,"P",0,1))return Duration.parse(t.toUpperCase(Locale.ROOT));var m=SHORT_DURATION.matcher(t);if(!m.matches())throw new IllegalArgumentException();long a=Long.parseLong(m.group(1));return switch(m.group(2).toUpperCase(Locale.ROOT)){case "MS"->Duration.ofMillis(a);case "S"->Duration.ofSeconds(a);case "M"->Duration.ofMinutes(a);case "H"->Duration.ofHours(a);case "D"->Duration.ofDays(a);default->throw new IllegalArgumentException();};}
    private static BigDecimal parseSize(String value){var m=SIZE.matcher(value.trim());if(!m.matches())throw new IllegalArgumentException();BigDecimal a=new BigDecimal(m.group(1));String u=m.group(2)==null?"B":m.group(2).toUpperCase(Locale.ROOT);BigDecimal x=switch(u){case "B"->BigDecimal.ONE;case "KB"->BigDecimal.valueOf(1_000L);case "MB"->BigDecimal.valueOf(1_000_000L);case "GB"->BigDecimal.valueOf(1_000_000_000L);case "TB"->BigDecimal.valueOf(1_000_000_000_000L);case "KIB"->BigDecimal.valueOf(1_024L);case "MIB"->BigDecimal.valueOf(1_048_576L);case "GIB"->BigDecimal.valueOf(1_073_741_824L);case "TIB"->BigDecimal.valueOf(1_099_511_627_776L);default->throw new IllegalArgumentException();};return a.multiply(x);}
    private static String typeMessage(EnvType type){return switch(type){case URL->"malformed URL";case URI->"malformed URI";case INTEGER->"must be an integer";case LONG->"must be a long integer";case BOOLEAN->"must be true or false";case HOST->"malformed host";case PORT->"must be a port between 1 and 65535";case DURATION->"malformed duration";case SIZE->"malformed data size";case STRING->"invalid string";};}
}
